"""Static reference data for the internal StreamWatch Methods page."""

METHODS_SUBTITLE = (
    "Reference information for StreamWatch monitoring methods, equipment, "
    "activity types, and historical changes."
)

CHLORIDE_NOTE = (
    "In 2026, a chloride standard-preparation error was discovered. The "
    "Watershed source states that discrete-analyzer chloride measurements "
    "\"to date\" were divided by 10, and that 2026 report cards were also "
    "adjusted. This page is documentation only and does not confirm that "
    "every chloride value in this database has already been corrected."
)

METHOD_ROWS = [
    {
        "parameter": "Water Temperature",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "deg C",
        "limit": "Lower Quantitation Limit / Upper Quantitation Limit",
        "equipment": "Alcohol thermometer (LaMotte setup); Hanna multimeter in current setup",
        "effective_period": "1992-present; Hanna introduced 2023",
        "notes": "CAT methods vary over time; current setup depends on site.",
    },
    {
        "parameter": "Air Temperature",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "deg C",
        "limit": "-5.00 to 55.00 deg C",
        "equipment": "Unclear in source",
        "effective_period": "1992-present",
        "notes": "DataDictionary describes this as air temperature measured in celsius.",
    },
    {
        "parameter": "pH",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "pH units not specified",
        "limit": "0.2 OR 1",
        "equipment": "LaMotte kit historically; Hanna multimeter in current setup",
        "effective_period": "1992-present; Hanna introduced 2023",
        "notes": "The source table shows an ambiguous limit value and should not be normalized further.",
    },
    {
        "parameter": "Dissolved Oxygen",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "mg/L",
        "limit": "0.01 ppm",
        "equipment": "LaMotte kit historically; Hanna multimeter in current setup",
        "effective_period": "1992-present; Hanna introduced 2023",
        "notes": "DataDictionary states DO ppm is measured in mg/L.",
    },
    {
        "parameter": "Conductivity",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "uS/cm",
        "limit": "Not specified",
        "equipment": "Hanna multimeter",
        "effective_period": "2023 onward",
        "notes": "The summary states conductivity/salinity is measured from 2023 onward.",
    },
    {
        "parameter": "Turbidity",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "Not specified",
        "limit": "4.5 OR 10",
        "equipment": "LaMotte kit historically",
        "effective_period": "1992-present; method changed mid-late 2010",
        "notes": "Source notes a turbidity method change in mid-late 2010 and preserves an ambiguous limit.",
    },
    {
        "parameter": "Nitrate",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "ug/L",
        "limit": "Not specified",
        "equipment": "LaMotte kit historically",
        "effective_period": "1992-2022 primarily; transition after 2023",
        "notes": "The field nitrate row in the source does not list a numeric detection or quantitation limit.",
    },
    {
        "parameter": "Phosphate",
        "program": "CAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs",
        "units": "mg/L",
        "limit": "0.2",
        "equipment": "LaMotte kit historically",
        "effective_period": "1992-2022 primarily; transition after 2023",
        "notes": "Field phosphate is listed separately from later lab phosphate entries.",
    },
    {
        "parameter": "Nitrate",
        "program": "BACT / CAT transition",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "ug/L",
        "limit": "0.2",
        "equipment": "Gallery discrete analyzer",
        "effective_period": "BACT from 2021; CAT transition beginning 2023/2024",
        "notes": "The summary states BACT begins nutrient grab samples in 2021 and CAT transitions to lab analysis in 2023/2024.",
    },
    {
        "parameter": "Phosphate",
        "program": "BACT / CAT transition",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "mg/L",
        "limit": "0.2 OR 1",
        "equipment": "Gallery discrete analyzer",
        "effective_period": "BACT from 2021; CAT transition beginning 2023/2024",
        "notes": "The source preserves two possible lab phosphate limits.",
    },
    {
        "parameter": "Turbidity",
        "program": "BACT / CAT transition",
        "field_lab": "Field",
        "activity_type": "Sample-Routine",
        "units": "Not specified",
        "limit": "Not specified",
        "equipment": "Hach turbidimeter",
        "effective_period": "Current methodology in source; exact start unclear",
        "notes": "The summary lists Hach turbidimeters in current CAT and BACT methodology, but does not provide a single effective date.",
    },
    {
        "parameter": "Chloride - High",
        "program": "BACT / CAT transition",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "mg/L",
        "limit": "8.38 mg/L",
        "equipment": "Gallery discrete analyzer",
        "effective_period": "BACT from 2021; CAT transition beginning 2023/2024",
        "notes": "See the 2026 chloride correction note below; this page does not apply any correction.",
    },
    {
        "parameter": "Nitrite",
        "program": "BACT / CAT transition",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "u/l",
        "limit": "0 u/l",
        "equipment": "Gallery discrete analyzer",
        "effective_period": "BACT from 2021; CAT transition beginning 2023/2024",
        "notes": "The summary spells this as Nitrite with a zero lower limit in the table.",
    },
    {
        "parameter": "Phosphorous / Phosphorus",
        "program": "BACT / CAT transition",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "mg/l",
        "limit": "0.01651 mg/l",
        "equipment": "Gallery discrete analyzer",
        "effective_period": "BACT from 2021; CAT transition beginning 2023/2024",
        "notes": "The primary summary spells this analyte as Phosphorous.",
    },
    {
        "parameter": "Total Nitrogen",
        "program": "BACT / CAT transition",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "u/l",
        "limit": "306.1 u/l",
        "equipment": "Gallery discrete analyzer",
        "effective_period": "BACT from 2021; CAT transition beginning 2023/2024",
        "notes": "Units appear in the source as u/l and are shown here without further interpretation.",
    },
    {
        "parameter": "E. coli",
        "program": "BACT",
        "field_lab": "Lab",
        "activity_type": "Sample-Routine",
        "units": "MPN/100 mL",
        "limit": "1 Organism / 100 mL",
        "equipment": "Coliscan Easygel historically; IDEXX/Colilert from 2015",
        "effective_period": "2007-present; method changed 2015",
        "notes": "The timeline says IDEXX/Colilert from 2015, while a later BACT section says Idexx colisure tests for the past 10-12 years.",
    },
    {
        "parameter": "Macroinvertebrate",
        "program": "BAT",
        "field_lab": "Field / Lab",
        "activity_type": "Sample-Field Subsample; Sample-Other; Sample-Routine",
        "units": "Not specified",
        "limit": "Not specified",
        "equipment": "Benthic macroinvertebrate survey",
        "effective_period": "1995-present",
        "notes": "Identified to family level through 2018; from 2018 onward at least one event per year is identified to species level by a certified lab.",
    },
    {
        "parameter": "Macroinvertebrate QC",
        "program": "BAT",
        "field_lab": "Lab",
        "activity_type": "Quality Control Sample-Blind Duplicate; Quality Control Sample-Lab Re-Analysis",
        "units": "Not specified",
        "limit": "Not specified",
        "equipment": "Certified lab re-analysis context",
        "effective_period": "Not specified",
        "notes": "The methods table lists QC activity types but does not attach a date range in the same section.",
    },
    {
        "parameter": "Bug Count",
        "program": "BAT",
        "field_lab": "Field / Lab",
        "activity_type": "Sample-Routine",
        "units": "Count",
        "limit": "Not specified",
        "equipment": "Volunteer counts historically; certified lab identification in later workflow",
        "effective_period": "1995-present; certified lab only from 2024",
        "notes": "The 2024 WQX workbook also uses Sample-Composite With Parents for count results, so export phrasing varies by source.",
    },
    {
        "parameter": "Habitat assessment",
        "program": "BAT",
        "field_lab": "Field",
        "activity_type": "Field Msr/Obs-Habitat Assessment",
        "units": "Not specified",
        "limit": "Not specified",
        "equipment": "Visual habitat assessment using USEPA Rapid Bio-Assessment Protocol",
        "effective_period": "1995-present",
        "notes": "Used to rate physical influences on stream communities and identify habitat limitations.",
    },
]

TIMELINE_EVENTS = [
    {"year": "1992", "event": "CAT founded; volunteers begin collecting data twice a month."},
    {"year": "1995", "event": "BAT founded; volunteers begin collecting data three times per year in spring, summer, and fall."},
    {"year": "2007", "event": "BACT founded; quarterly bacteria sampling begins using Coliscan Easygel."},
    {"year": "2010", "event": "CAT changes from bi-weekly to monthly sampling."},
    {"year": "Mid-late 2010", "event": "CAT changes turbidity method."},
    {"year": "2015", "event": "BACT switches from Coliscan Easygel to IDEXX/Colilert."},
    {"year": "2018", "event": "BAT frequency changes from three times per year to two; spring and fall sampling alternates volunteer and certified-lab identifications."},
    {"year": "2021", "event": "BACT begins grab samples for nutrient analysis with a discrete analyzer."},
    {"year": "2023", "event": "CAT introduces Hanna meters and use of a discrete analyzer; conductivity begins from 2023 onward."},
    {"year": "2024", "event": "BAT decreases to once-per-spring sampling using certified-lab identifications exclusively."},
    {"year": "2026", "event": "Chloride standard-preparation error discovered; source says discrete-analyzer chloride measurements to date were divided by 10 and 2026 report cards were adjusted."},
    {"year": "Discontinued", "event": "River Action Team / StreamWalking discontinued; quarterly visual stream-corridor and habitat assessments were historical only."},
]

SOURCE_NOTES = [
    "Primary source: StreamWatch Data Summary & Description, last updated Aug. 31, 2026.",
    "Supporting source material used here includes DataDictionary and the 2024 WQX submission workbook.",
    "Blank or ambiguous method fields are shown as unresolved rather than inferred.",
    "Historical methods and activity types may differ by year and program.",
    "This page documents Watershed source materials; it does not independently define scientific policy.",
]
